### ISSUE TITLE
LV2 (and CLAP) target?

### ISSUE THREAD

**Issue by mxmilkiib** [ssabug/choppah#20]
Hi! I am wondering if you would be willing to add building to the LV2 plugin format (and CLAP format) to the project? Thanks!

**Comment by ssabug** [comment]
Hi, 
There's no reason not to add LV2/CLAP support for me, i just did not added them yet.
I think you can already add them by yourself by modifying the .jucer file if you want to try.
I'm not sure if CLAP support is built-in in JUCE.

**Comment by ssabug** [comment]
@mxmilkiib there is a LV2 build in v0.1 to be tested on Linux
